---
title: 'Week 13: Alcohol COnsumption in Africa'
author: "Fanice M Nyatigo"
date: "03/07/2018"
output:
  github_document: default
  pdf_document: default
---

## Loading Packages...

```{r}
library(tidyverse)
library(ggthemes)
library(countrycode)

```

## Reading Data

```{r}

alcohol <- read_csv("https://raw.githubusercontent.com/JoeSalami/MyTidyTuesday/master/Week%2013/Data/week13_alcohol_global.csv")

alcohol$country <- as.factor(alcohol$country)
alcohol$continent <- factor( countrycode(sourcevar = alcohol$country,
                                     origin = 'country.name',
                                     destination = 'continent'))
micronesia <- !is.na(alcohol$continent)
alcohol <- alcohol[micronesia,]

```

## Subsetting Africa

```{r}
alcohol <- alcohol %>% mutate(total_servings = beer_servings + spirit_servings +   wine_servings) %>%
         select(country, continent, beer_servings, spirit_servings, 
                wine_servings, total_servings, total_litres_of_pure_alcohol) 

africa_alc <- alcohol %>% filter(continent == 'Africa') %>%
              arrange(desc(total_servings))
              
africa_alc_dist <- africa_alc %>% top_n(20, total_servings) %>% 
                gather(key = alcohol.type, value = servings, 
                        beer_servings, spirit_servings, wine_servings)


```

## Distribution of Alcohol Consumption in Africa

```{r Africa_Alcohol_Distribution}

ggplot(africa_alc_dist, aes(x= reorder(country, servings),y=servings))+
  geom_bar(stat="identity", aes(fill = alcohol.type))+ 
  coord_flip() +
  scale_x_discrete(expand = c(.02, 0)) +
  labs(title = "Top 20 Alcohol Consumers In Africa",
  subtitle = "The highest consumers of alcohol (beer, wine, or spirits) in Africa",
       caption= "Data:FiveThirtyEight \nBy: @JoeSalami",
       x = "",
       y = "Servings of Alcohol",
       fill = "Alcohol Type") +
  theme(text = element_text(size = 11,colour= "black"),
               plot.title = element_text(face = "bold", size = 20),
               legend.title = element_text(face = 'bold')) +
  theme_light() 

# ggsave("Africa_Alcohol_Distribution.jpg", path = path)

```

## Top 10 Beer consuming African countries

```{r Africa_Beer_Consumers}
africa_alc %>% top_n(10, beer_servings) %>%
ggplot(aes(x= reorder(country, beer_servings),y=beer_servings))+
  geom_bar(stat="identity", aes(fill = country))+
  coord_flip() +
  labs(title = "Top 10 Beer Consumers In Africa",
       caption= "Data:FiveThirtyEight \nBy: @JoeSalami",
       x = "",
       y = "Servings of Beer",
       fill = "Country") + 
  theme_light()+
  theme(text = element_text(size = 11,colour= "black"),
               plot.title = element_text(face = "bold", size = 20),
               legend.position = 'none')
# ggsave("Africa_Beer_Consumers.jpg", path = '~/GitHub/MyTidyTuesday/Week 13/Images')
```

## Top 10 Wine consuming African countries

```{r Africa_Wine_Consumers}
africa_alc %>% top_n(10, wine_servings) %>%
ggplot(aes(x= reorder(country, wine_servings),y=wine_servings))+
  geom_bar(stat="identity", aes(fill = country))+
  coord_flip() +
  labs(title = "Top 10 Wine Consumers In Africa",
       caption= "Data:FiveThirtyEight \nBy: @JoeSalami",
       x = "",
       y = "Servings of Wine",
       fill = "Country") + 
  theme_light()+
  theme(text = element_text(size = 11,colour= "black"),
               plot.title = element_text(face = "bold", size = 20),
               legend.position = 'none')
# ggsave("Africa_Wine_Consumers.jpg", path = '~/GitHub/MyTidyTuesday/Week 13/Images')
```

## Top 15 Spirit consuming African countries

```{r Africa_Spirits_Consumers}
africa_alc %>% top_n(10, spirit_servings) %>%
ggplot(aes(x= reorder(country, spirit_servings),y=spirit_servings))+
  geom_bar(stat="identity", aes(fill = country))+
  coord_flip() +
  labs(title = "Top 10 Spirits Consumers In Africa",
       caption= "Data:FiveThirtyEight \nBy: @JoeSalami",
       x = "",
       y = "Servings of Spirits",
       fill = "Country") +
  theme_light()+
  theme(text = element_text(size = 11,colour= "black"),
               plot.title = element_text(face = "bold", size = 20),
               legend.position = 'none')
# ggsave("Africa_Spirits_Consumers.jpg", path = '~/GitHub/MyTidyTuesday/Week 13/Images')
```

